name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore ./CityAid.Api/CityAid.Api.csproj
    - name: Build
      run: dotnet build --no-restore -c Release ./CityAid.Api/CityAid.Api.csproj
    - name: Test (none yet)
      run: echo "No tests yet"
